drop table if exists usuarios;
drop table if exists coordenadas;
drop table if exists detalle_coordenadas;

create table detalle_coordenadas
(
    id_detalle_coordenadas bigint generated by default as identity
        primary key,
    detalle_latitud        varchar(255),
    detalle_longitud       varchar(255)
);

alter table detalle_coordenadas
    owner to javiernavarro;

create table coordenadas
(
    id_coordenadas         bigint generated by default as identity
        primary key,
    latitud                varchar(255) not null,
    longitud               varchar(255) not null,
    id_detalle_coordenadas bigint
        constraint fk5kxjr6nwe57mdftad21rprl71
            references detalle_coordenadas
);

alter table coordenadas
    owner to javiernavarro;

create table usuarios
(
    id_usuarios bigint generated by default as identity
        primary key,
    password    varchar(255),
    username    varchar(255)
);

alter table usuarios
    owner to javiernavarro;
